update asyncplusplus
This resolves the following errors:

clang++ -c -pipe -Wno-deprecated-enum-enum-conversion -Wno-missing-field-initializers -Wno-unused-function -Wno-unused-parameter -g -O2 -std=gnu++2a -pthread -Wall -Wextra -D_REENTRANT -fPIC -DFLATPAK_APP_ID=\"me.timschneeberger.jdsp4linux\" -DAPP_VERSION=8493af9 -DJDSP_VERSION=4.01 -DQT_NO_PRINTER -DQTCSV_MAKE_LIB -DHAS_JDSP_DRIVER -DADS_STATIC -DQT_DEPRECATED_WARNINGS -D_REENTRANT -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../src -I. -I../../3rdparty/asyncplusplus/include -I../../3rdparty/qtpromise/include -I../../3rdparty/qtpromise/src -I../../3rdparty/qcustomplot -I../../3rdparty/qtcsv/include -I../../3rdparty/qtcsv -I../../3rdparty/WAF -I../../3rdparty -I../../src/audio/base -I../../src/audio/pipewire -I../../src/subprojects/AutoEqIntegration -I../../src/subprojects/FlatTabWidget/FlatTabWidget -I../../src/subprojects/LiquidEqualizerWidget/src -I../../src/subprojects/GraphicEQWidget/GraphicEQWidget -I../../src/subprojects/EELEditor/3rdparty/QCodeEditor/include -I../../src/subprojects/EELEditor/3rdparty/docking-system/src -I../../src/subprojects/EELEditor/src -I../../libjamesdsp/subtree/Main/libjamesdsp/jni/jamesdsp/jdsp -I../../libjamesdsp -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/include/giomm-2.4 -I/usr/lib64/giomm-2.4/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui/5.15.10 -I/usr/include/qt5/QtGui/5.15.10/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore/5.15.10 -I/usr/include/qt5/QtCore/5.15.10/QtCore -I/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-clang -o scheduler.o ../../3rdparty/asyncplusplus/src/scheduler.cpp
In file included from ../../3rdparty/asyncplusplus/src/scheduler.cpp:21:
In file included from ../../3rdparty/asyncplusplus/src/internal.h:34:
In file included from ../../3rdparty/asyncplusplus/include/async++.h:143:
../../3rdparty/asyncplusplus/include/async++/task.h:477:49: error: no type named 'result_of' in namespace 'std'
task<typename detail::remove_task<typename std::result_of<typename std::decay<Func>::type()>::type>::type> spawn(Sched& sched, Func&& f)
                                  ~~~~~~~~~~~~~~^~~~~~~~~
../../3rdparty/asyncplusplus/include/async++/task.h:477:99: error: expected unqualified-id
task<typename detail::remove_task<typename std::result_of<typename std::decay<Func>::type()>::type>::type> spawn(Sched& sched, Func&& f)
                                                                                                  ^
In file included from ../../3rdparty/asyncplusplus/src/scheduler.cpp:21:
In file included from ../../3rdparty/asyncplusplus/src/internal.h:34:
In file included from ../../3rdparty/asyncplusplus/include/async++.h:144:
../../3rdparty/asyncplusplus/include/async++/when_all_any.h:255:16: error: no member named 'make_task' in namespace 'async'
        return async::make_task(std::tuple<>());
               ~~~~~~~^
../../3rdparty/asyncplusplus/include/async++/when_all_any.h:275:16: error: no member named 'make_task' in namespace 'async'
        return async::make_task(when_any_result<std::tuple<>>());
               ~~~~~~~^
In file included from ../../3rdparty/asyncplusplus/src/scheduler.cpp:21:
In file included from ../../3rdparty/asyncplusplus/src/internal.h:34:
In file included from ../../3rdparty/asyncplusplus/include/async++.h:148:
../../3rdparty/asyncplusplus/include/async++/parallel_invoke.h:34:21: error: no member named 'local_spawn' in namespace 'async'
                auto&& t = async::local_spawn(sched, [&sched, &args] {
                           ~~~~~~~^
In file included from ../../3rdparty/asyncplusplus/src/scheduler.cpp:21:
In file included from ../../3rdparty/asyncplusplus/src/internal.h:34:
In file included from ../../3rdparty/asyncplusplus/include/async++.h:149:
../../3rdparty/asyncplusplus/include/async++/parallel_for.h:42:20: error: no member named 'local_spawn' in namespace 'async'
        auto&& t = async::local_spawn(sched, [&sched, &subpart, &func] {
                   ~~~~~~~^
In file included from ../../3rdparty/asyncplusplus/src/scheduler.cpp:21:
In file included from ../../3rdparty/asyncplusplus/src/internal.h:34:
In file included from ../../3rdparty/asyncplusplus/include/async++.h:150:
../../3rdparty/asyncplusplus/include/async++/parallel_reduce.h:52:20: error: no member named 'local_spawn' in namespace 'async'
        auto&& t = async::local_spawn(sched, [&sched, &subpart, init, &map, &reduce] {
                   ~~~~~~~^
7 errors generated.
make[1]: *** [Makefile:2889: scheduler.o] Error 1